### ISSUE TITLE
Wrong type on MousePosition

### ISSUE THREAD

**Issue by tkacenkoradim** [FlaxEngine/FlaxAPI#1]
Hey,

I've probably found a "bug", the property MousePosition in GUI/Window.cs (line 98) is marked as bool instead of Vector2... this is also in Window.Gen.cs (line 98, 621 and 623).

I originally wanted to pull my edits but, because the edits would be in generated part of API i rejected that idea.

**Comment by Muchaszewski** [comment]
Thanks for reporting this issue! This sure is a bug. I wonder only how it worked until this point :)

**Comment by tkacenkoradim** [comment]
Well it's unused property so... it's used only on these two places and probably isn't even called on C++ side (my theory)

**Comment by mafiesto4** [comment]
Good catch! On C++ side we were putting a proper `Vector2` value but I still don't understand how it was working. Anyway, it gets fixed.
