### ISSUE TITLE
Not consistant OnCollisionEnter/Exit behavior

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#10]
OnCollisionExit is called when Rigidbody stops overlapping another collider. OnCollisionEnter is not called again even if Exit was previously called and rigidbody is in sitting on a collider (due to gravity).
OnCollisionStay is called in that state.

Expected logic:
OnCollisionEnter - Is called once when collider begins collision with another collider
OnCollisionStay - Is called each fixed update when collider touches with another collider (One fixed update after Enter)
OnCollisionExit - Is called when collider ends collision with another collider

![image](https://user-images.githubusercontent.com/5092066/40268138-aa178d1c-5b68-11e8-9bd1-85cdeebe3999.png)

![image](https://user-images.githubusercontent.com/5092066/40268222-e139d704-5b69-11e8-937e-efebc08accd2.png)
OnCollisionExit is not called sometimes

Snipset - Attach to rigidbody with collider
```
using FlaxEngine;

namespace MyProject
{
	public class Script0 : Script
	{

	    private void OnCollisionEnter(Collision c)
	    {
	        Debug.Log("OnCollisionEnter");
	    }

        private void OnCollisionStay(Collision c)
	    {
	        Debug.Log("OnCollisionStay");
	    }

	    private void OnCollisionExit(Collision c)
	    {
	        Debug.Log("OnCollisionStay");
	    }
    }
}

```

**Comment by mafiesto4** [comment]
Fixed.
