### ISSUE TITLE
Message wrong signature gets executed

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#11]
Signature
```
            private void OnCollisionStay(int c)
	    {
	        Debug.Log("OnCollisionStay" + c);
	    }
```

Is called with value int as 963088312 (changes every execution)

Expected result:
Do not call OnCollisionStay or ignore parameter

Signature
```
            private void OnCollisionStay(string c)
	    {
	        Debug.Log("OnCollisionStay" + c);
	    }
```

Throws an exception 
![image](https://user-images.githubusercontent.com/5092066/40268264-89f48e0c-5b6a-11e8-92e7-91c7a7f458e1.png)

Expected result:
Do not call OnCollisionStay or ignore parameter

Signature
```
            int foo= 0;

            private void OnCollisionStay(Script0 c)
	    {
	        Debug.Log("OnCollisionStay" + c.foo);
	    }
```

1) Creates new default instance
2) Changes value of foo to random integers

Expected result:
Do not call OnCollisionStay or ignore parameter or throw an exception

Signature
```
            int foo= 0;

            private void OnCollisionStay(Script0 c, int d)
	    {
	        Debug.Log("OnCollisionStay" + c.foo + " " + d);
	    }
```

Method is called (once) but all parameters are null?
![image](https://user-images.githubusercontent.com/5092066/40268307-41be7c64-5b6b-11e8-9c8c-9f489b20d5cf.png)

Expected result:
Do not call OnCollisionStay or ignore parameters or throw an exception

**Comment by mafiesto4** [comment]
Fixed. Collision and trigger event functions are gathered using full signature validation.
