### ISSUE TITLE
Content text when wrapping goes out of items bound

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#12]
![image](https://user-images.githubusercontent.com/5092066/40499529-7f935a30-5f82-11e8-929a-1cc3016aaf1b.png)

Text should be centered (In this case moved more to left) and any pixel should not go pass the items box

* Windows 10 x64
* Flax 0.1.6155

**Comment by mafiesto4** [comment]
Fixed.
