### ISSUE TITLE
try-catched exceptions are cached multiple times

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#15]
When throwing an exception its cached internally even if manually try-catched

```
try
{
	throw new Exception("E");
}
catch (Exception e)
{
	Debug.LogException(e);
}
```

![image](https://user-images.githubusercontent.com/5092066/40802258-611668ac-6515-11e8-9379-323397e82333.png)
![image](https://user-images.githubusercontent.com/5092066/40802260-64312f04-6515-11e8-9707-c0167eea3aa3.png)

Expected result:
The exception is only displayed once on LogException debug log.

**Comment by mafiesto4** [comment]
Fixed for ver 0.8.
