### ISSUE TITLE
Another round of typos

### ISSUE THREAD

**Issue by tkacenkoradim** [FlaxEngine/FlaxAPI#2]
Hey it's me again, I've found few typos when digging through generated API

- BoxBrush's UsePerspective property should be named ScaleInLightmap (based on internal calls + summary)
- DirectionalLight's ShadowsMode and MinimumRoughness properties have switched Internal calls corresponding with them
- PhysicalActor doesn't have .Gen.cs counterpart (I'm not sure if it's a bug or not)
- PointLight's ScaledRadius calls Get/SetSourceLength instead of Get/SetScaledRadius... MinimumRoughness and Color property are missing summaries (they are blank)

**Comment by mafiesto4** [comment]
Thanks again for your help! 👍 🥇
