### ISSUE TITLE
ShowInEditor attribute revert value to default

### ISSUE THREAD

**Issue by Meretto** [FlaxEngine/FlaxAPI#23]
**Problem:** When I change BallSpeed value to 100 in editor, press enter and click start simulation. Value back to 30

**My code:**

```
using System;
using System.Collections.Generic;
using FlaxEngine;

namespace Pong
{
	public class ActorBall : Script
	{
        [ShowInEditor] private float BallSpeed = 30f;
        private RigidBody rigidBody;

        private void Awake()
        {
            rigidBody = this.Actor as RigidBody;
        }
        private void FixedUpdate()
        {
            rigidBody.LinearVelocity = Vector3.Right * BallSpeed;
        }
}
}
```

**Comment by mafiesto4** [comment]
That's because `private` fields are not serialized by default. 
To fix it just add ` Serialize` attribute to the BallSpeed field like that:
```cs
[ShowInEditor, Serialize] private float BallSpeed = 30f;
```
See serialization rules listed in a documentation here: https://docs.flaxengine.com/manual/scripting/serialization/index.html

**Comment by Meretto** [comment]
Attribute like this will be better for debug https://answers.unity.com/questions/489942/how-to-make-a-readonly-property-in-inspector.html
