### ISSUE TITLE
Add layers and tags doesn't work

### ISSUE THREAD

**Issue by Meretto** [FlaxEngine/FlaxAPI#24]
**Problem:**
1. Create Blank project
2. Create new scene
3. Create Game Settings
4. Create Layer And Tags Settings
5. Assign Layer And Tags Settings to Game Settings
6. Open Layer And Tags Settings and add new layer/tag
7. There is no option on object what we added
8. Restart project solving a problem

![image](https://user-images.githubusercontent.com/41115906/42864750-c9f8c0c8-8a67-11e8-90a1-97a37d29e5a1.png)

**Comment by mafiesto4** [comment]
Thanks for the report. That is already known case, the documentation explains it here: https://docs.flaxengine.com/manual/editor/game-settings/layers-and-tags-settings.html
