### ISSUE TITLE
Beta Release

### ISSUE THREAD

**Issue by amerkoleci** [FlaxEngine/FlaxAPI#3]
Hi,
Excellent work on your engine, I'm also working on .NET game engine with Vulkan, DirectX12 and Metal, probably will emulate some next gen rendering features (like CommandBuffer) on OpenGL for mobile, the engine is here https://github.com/amerkoleci/Alimer and I will start to commit code from my private repository there.

Any plan to have some beta/WIP release? 
I saw you've done lot of job but at the moment is not possible to test anything.

Thanks,
Amer

**Comment by mafiesto4** [comment]
Hey, yeah there is a lot of stuff going on with the project right now. I anticipate the first beta release in Spring 2018. Probably some closed alpha before but there is still a lot of features I want to put into the engine.

Also read our de blog here: http://flaxengine.com/blog
