### ISSUE TITLE
Main Editor Viewport Invisible Something

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#30]
In the main editor window, where you can look at the scene and edit it, there seems to be a small, invisible something. The approximate location of it has been marked in the image:
![image](https://user-images.githubusercontent.com/10220080/45589012-8e28dc00-b91e-11e8-9ad7-1cd0b4030d68.png)

When you right click there, instead of being able to drag the scene, nothing happens.

**Comment by mafiesto4** [comment]
That's very interesting! But confirmed, I'll fix it.

**Comment by mafiesto4** [comment]
Fixed.
