### ISSUE TITLE
TextRender only displaying a part of the string

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#38]
I'm not sure if this is a bug with Flax or if I just messed up something. 

Anyways, I just modified <https://github.com/stefnotch/keyboard-letters-game> to "properly" handle multiple keys being pressed at the same time. However, the `TextRender` doesn't seem to always cooperate. It quite frequently messes up and only shows one or 2 keys instead of all of them.
e.g. Something like `FxEg` instead of `FlaxEngine`. Or, `w` instead of `aw`.

### To reproduce:
1) Download the latest code ( <https://github.com/stefnotch/keyboard-letters-game> )
2) Open it with Flax
3) Play around with it 
4) Make sure your keyboard can actually handle multiple keys being pressed at the same time (keyboard rollover)
5) Spam a lot of keys at the same time
6) Bug should occur.

### Screenshot:
![image](https://user-images.githubusercontent.com/10220080/47593516-ef10ee80-d977-11e8-927e-e2d87278a95f.png)
As you can see, the code is setting "WADS" as the string, however only "WAD" gets displayed.

**Comment by mafiesto4** [comment]
Already fixed on dev branch. Wait for the update.
