### ISSUE TITLE
Change is script type if script is attached results in a crash

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#4]
- Create new Script.
- Attach the script to object in the scene within its properties
- Edit Script. Change its type from Script to for example Actor
- Reload Scripts (or wait for auto reload)
- Select object in the scene that we had attached our script to.
- Crash 100%

* Windows 10 64x
* Flax 0.1

**Comment by mafiesto4** [comment]
Fixed
