### ISSUE TITLE
Programatically reimporting ContentItems

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#41]
**Issue description:**

I attempted to automatically reimport files when their source file changes. However, sometimes, I was faced with the following error:

```
Assertion failed!
File: Engine\Content\Storage\FlaxStorage.cpp
Line: 1057

Expression: _chunksLock == 0
```

**Steps to reproduce:**

It's a bit hard to reproduce; usually it takes quite a number of edits in various files until the error occurs.

Also, after the error happens, this happens when I try to clean up the temporary files I created:
![image](https://user-images.githubusercontent.com/10220080/48318252-be7ab700-e5fd-11e8-8207-b82f1ec3d7be.png)

The [following code](https://github.com/stefnotch/flax-auto-import-resources-plugin/blob/98fe4dde66a9dc46430a11b04d346a00e57e0883/Source/Editor/ResourcePlugin.cs#L318) seems to cause it.
```csharp
BinaryAssetItem item = Editor.ContentDatabase.Find(SOMEPATH) as BinaryAssetItem;
if (FlaxEngine.Content.Load(item.ID) is BinaryAsset test)
{
    test.WaitForLoaded();
    test.Reimport();
}
```

**Minimal reproduction project:**

https://github.com/stefnotch/flax-auto-import-resources-plugin

**Flax version:** v0.2

**Comment by stefnotch** [comment]
I also attempted to reimport stuff like this
```csharp
Editor.ContentImporting.Reimport(item); 
```
However, this causes the Import dialog to pop up every single time, which is rather inconvenient.

**Comment by stefnotch** [comment]
I'll probably use this for now:

https://github.com/FlaxEngine/FlaxAPI/blob/9f3b7e4d417c2c1d668462be560f3359fc863f2f/FlaxEditor/Content/Import/ImportFileEntry.cs#L88

**Comment by mafiesto4** [comment]
Thanks for the report! It's related to one of the issues with content files locking in C++ by async tasks. It should be fixed by the next update. Also, we could add API for importing assets from code via API without popups.

**Comment by stefnotch** [comment]
Ok, looking forward to the update! 😄 

> Also, we could add API for importing assets from code via API without popups.

That sounds pretty useful. So, I'd love to see that API get implemented. (Something like the current `.Reimport()`, but with an optional parameter `showImportPopup = true` would be nice.)

**Comment by stefnotch** [comment]
Ok, [this](https://github.com/FlaxEngine/FlaxAPI/commit/4f558465aaa03427ed076a474ae33953cb517a22) works beautifully. Thank you!
