### ISSUE TITLE
Changing First Scene Bug/Crash

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#42]
**Issue description:**

The following errors may pop up
```
Actors Cache already contains actor Scene (Scene; 74a68a984824b4510d12589f199ad68f)!
```
and
```
Objects registry already contains object with ID=74a68a984824b4510d12589f199ad68f! Trying to register object Scene (Scene; 74a68a984824b4510d12589f199ad68f).
```
and
```
Assertion failed!
File: Engine\Scripting\ScriptingEngine.cpp
Line: 560

Expression: !obj->_id.IsValid() || _objectsDictionary.ContainsValue(obj)
```

**Steps to reproduce:**

1) Delete the `Cache` folder
2) Open the project
3) Create a new scene
4) Open the GameSettings
5) Change the `First Scene` to that new scene
6) Save the GameSettings
7) Open that new scene, open the previous scene, ... 

**Minimal reproduction project:**

**Flax version:**

v0.3

**Comment by mafiesto4** [comment]
Thanks for the report! Issue fixed in https://github.com/FlaxEngine/FlaxAPI/commit/234ed85d88523bf4b3422e3b321f43009d46d189.
