### ISSUE TITLE
"Not supported operating system version."

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#43]
**Issue description:**

When attempting to open a project with Flax, the error message `Not supported operating system version.` pops up

**Steps to reproduce:**

1. Go to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion` (system registry)
2. Change the values of `CurrentMajorVersionNumber` and `CurrentMinorVersionNumber` to 0
3. Restart the PC
4. Attempt to open a Flax Project

**Minimal reproduction project:**

**Flax version:**

v0.3

**Comment by stefnotch** [comment]
## Fix
Change the values in the system registry to the correct values. 
`CurrentMajorVersionNumber` should be 6 or above

**Comment by stefnotch** [comment]
(Of course, if you're running Windows XP or below, Flax probably still won't run.)

**Comment by klukule** [comment]
And if anyone is reading this... the 6 and 3 depend on the version of Windows kernel, the numbers above are for Windows 8.1
