### ISSUE TITLE
Image UI Control does not respect depth, when Brush type is set to Material

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#44]
**Issue description:**

Image UI Control does not respect depth, when Brush type is set to Material.
![image](https://user-images.githubusercontent.com/10220080/50454313-f8521380-0946-11e9-9283-0560fdaa1c5d.png)
![image](https://user-images.githubusercontent.com/10220080/50454322-0e5fd400-0947-11e9-9f03-8557a41c9256.png)

**Steps to reproduce:**

1) UI Canvas
2) UI Control
3) Set type to Image
4) Add a brush
5) Set it to GUI material of your choice
6) Try to place a capsule in front of it. The material will always obscure the capsule.

**Minimal reproduction project:**

[KnightMiniJam.zip](https://github.com/FlaxEngine/FlaxAPI/files/2710728/KnightMiniJam.zip)

**Flax version:**

v0.3

**Comment by mafiesto4** [comment]
Thanks for the report! Fixed for version `0.3.6175`.
