### ISSUE TITLE
Profiler Timeline drawing text outside its bounding box

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#45]
**Issue description:**

When scrolling Profiler, text elements from timeline are displayed if they go out of bound in top right corner
![image](https://user-images.githubusercontent.com/5092066/51090342-db0caa00-177a-11e9-89fa-136919940de8.png)
![image](https://user-images.githubusercontent.com/5092066/51090361-24f59000-177b-11e9-94d3-afcc3aa6a0da.png)

**Steps to reproduce:**

Run profiler with elements that can be scrooled outside timeline window and scrolling is required.
Scroll down

**Minimal reproduction project:**

**Flax version:**

Flax 0.3.6176

**Comment by stefnotch** [comment]
This might be related:

The `top` you can read at the top, outside of the Visject Surface is the text from the `Get Parameter` node's dropdown
![image](https://user-images.githubusercontent.com/10220080/51202091-2ef3cc00-18fe-11e9-96ab-25d3193741c6.png)

![image](https://user-images.githubusercontent.com/10220080/51202138-5054b800-18fe-11e9-867e-137cfe02a336.png)

**Comment by mafiesto4** [comment]
Fixed in Flax 0.5.6187.
