### ISSUE TITLE
Debug timestamps

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#47]
Debug Logs should have timestamp (as present in logfile already)

Current
![image](https://user-images.githubusercontent.com/5092066/51355160-76bd5380-1ab6-11e9-93ad-5803d554d265.png)
Expected
![image](https://user-images.githubusercontent.com/5092066/51355195-a1a7a780-1ab6-11e9-8938-72760999f1e7.png)

**Comment by mafiesto4** [comment]
Added editor options for timestamps mode:
![image](https://user-images.githubusercontent.com/3464853/60978962-325a9400-a332-11e9-8cf5-e6dd019475ef.png)

**Time Since Startup** option:
![image](https://user-images.githubusercontent.com/3464853/60978837-09d29a00-a332-11e9-9f7e-a8c54a7f98b3.png)
