### ISSUE TITLE
AddScript button do not filters scripts by a valid type

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#5]
You can see and select items that are not a valid type on the list with following error.

![image](https://user-images.githubusercontent.com/5092066/40248135-2c4b38aa-5acf-11e8-892b-82ec6aea829b.png)
![image](https://user-images.githubusercontent.com/5092066/40248155-3def6784-5acf-11e8-8bbb-a61a19b8a95d.png)

Steps:
* Create new Script.
* Edit Script. Change its type from Script to for example Actor
* Reload Scripts (or wait for auto reload)
* Select our new script from AddScript button
* Exception

**Comment by mafiesto4** [comment]
Fixed
