### ISSUE TITLE
Generic Script Constructors

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#54]
**Issue description:**

I've been trying to make something akin to constructors for generic scripts.

**Steps to reproduce:**

Add the following script
```csharp
public class GenericScript<T> : Script
{
    public static GenericScript<T> Make()
    {
        var script = New<GenericScript<T>>();
        script.Enabled = false;

        return script;
    }

    public static GenericScript<U> Make<U>()
    {
        var script = New<GenericScript<U>>();
        script.Enabled = false;

        return script;
    }
}
```

Attempt to create an instance of it in some other script's `Start()` 
```csharp
// Simply crashes
var otherTest = GenericScript<Vector3>.Make();
Actor.AddScript(otherTest);
```

```csharp
// Also just crashes
var otherTest = GenericScript<Vector3>.Make<Vector3>();
Actor.AddScript(otherTest);
```

It should result in Flax crashing.

**Minimal reproduction project:**

**Flax version:**

0.3.6176

**Comment by mafiesto4** [comment]
Generic classes are not supported for script types. You need to add transition class such as (which will work fine):
```cs
public class GenericScriptTest :  GenericScript<Vector3>
{
    // ...
}
```

I'll add a dedicated check and warning log if a user tries to add generic type as a script.
