### ISSUE TITLE
Script Destroy this

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#55]
**Issue description:**

I tried to create a script that destroys itself after completing it's task

**Steps to reproduce:**

Apparently this causes a silent crash. If you add the `Enabled = false` line, it seems to work.

```csharp
public class Script0 : Script 
{
private void Start()
{
	//Enabled = false; // Can apparently prevent the crash
	Destroy(this);
}
private void Update()
{
	// Without "Update" Flax doesn't crash either
}
// It might also be possible to cause this by adding OnDisable() and whatnot
}
```

**Minimal reproduction project:**

**Flax version:**

0.3.6176

**Comment by mafiesto4** [comment]
Thanks for report. Fixed!
