### ISSUE TITLE
AddRelativeForce (0,0,0) without a collider moves the object

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#56]
**Issue description:**

I created a Rigidbody **without** a collider, created a script to move it, started the game (realized that I forgot the collider) and noticed that it exhibits a strange behaviour. Pretty sure that it's not supposed to start flying around like that.

![2019-02-11_16-49-40](https://user-images.githubusercontent.com/10220080/52574646-0e476500-2e1d-11e9-853a-6eb3f4a7172e.gif)

**Steps to reproduce:**

```csharp
public class ShipController : Script
{
  public RigidBody Ship; // Make sure that this rigidbody doesn't have a collider
  private void FixedUpdate()
  {
    Ship.AddRelativeForce(new Vector3(0, 0, 0));
  }
}
```

**Minimal reproduction project:**

**Flax version:**

0.3.6176

**Comment by stefnotch** [comment]
Upon further testing, I seem to still be able to reproduce this with a collider and gravity **disabled**.

**Comment by mafiesto4** [comment]
Ok I tested it and `AddRelativeForce` has issue in the current version. It has been fixed for the next update. Use `AddForce` for now.
