### ISSUE TITLE
Custom Editor creation 

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#59]
**Issue description:**

I have been trying to create a custom editor for an object and ran into an issue.
A `NullReferenceException` is being thrown by this method:
https://github.com/FlaxEngine/FlaxAPI/blob/36aa542d564c7b4f1d1115482730e9949c956749/FlaxEditor/CustomEditors/CustomEditorsUtil.cs#L76

**Steps to reproduce:**

`Editor/MyScriptEditor.cs`
```csharp
    public class Hi
    {
        public string test;
    }

    [CustomEditor(typeof(MyScript))]
    public class MyScriptEditor : GenericEditor
    {
        public override void Initialize(LayoutElementsContainer layout)
        {
            layout.Label("My Custom Editor", TextAlignment.Center);
            var group = layout.Group("Inner group");
            try
            {
                var n = new ValueContainer(typeof(Hi)) { new Hi() }; 
                layout.Object(n); // NullReferenceException
            }
            catch (Exception e)
            {
                Debug.LogError(e);
            }
            base.Initialize(group);
        }
    }
```
**Minimal reproduction project:**

**Flax version:**

0.4.6181

**Comment by stefnotch** [comment]
For future reference, an alternative is using a custom editor manually with proxy object like [here](https://github.com/FlaxEngine/FlaxAPI/blob/afa48a9997abee24064a79d7b7352a8356f9e405/FlaxEditor/Windows/Assets/MaterialWindow.cs#L463)
```
var x = new CustomEditorPresenter(null);
x.Panel.Parent = layout.ContainerControl;
x.Select(new Hi());
```

**Comment by mafiesto4** [comment]
You used the wrong values container implementation. For custom values access use `ReadOnlyValueContainer` or `CustomValueContainer` which gives even more flexibility.
