### ISSUE TITLE
After few compile-play cycles with diffrent code. Flax has returned to DLL compiled at the very begining

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#6]
There is no really reproduction steps, but general steps what has happened with no real reproduction yet.

- Lunch Flax with the prepared project that has a script attached to an Object `Update() {Debug.Log("T");}`
- Make modifications to the script, play the game, and repeat this point multiple times. (First modification should remove Debug.Log("T") for better effect)
- See after a few tries multiple things happen:
1. 
![image](https://user-images.githubusercontent.com/5092066/40249551-a26a2600-5ad3-11e8-85e0-5b9a02c83356.png) New Script with default values is attached
2. 
![image](https://user-images.githubusercontent.com/5092066/40249565-b0c72946-5ad3-11e8-80e7-92e29e93d2fd.png) T is logged again
3. Another reload has 50-50 chances of a crash or things will go back to normal (your current script)

* Windows 10 64x
* Flax 0.1.6154

**Comment by mafiesto4** [comment]
Unable to reproduce. Probably already fixed.
