### ISSUE TITLE
JSON Serializing private field from base class

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#60]
**Issue description:**

I'm not entirely sure if this is an issue or works as intended :tm: .

Anyways, I was using the FlaxEngine JSON serialisation and attempted to serialize a **private** field from the **base class**. To my surprise, this didn't work. 

(After a bit of digging, it seems that [this GetFields call right here](https://github.com/FlaxEngine/FlaxAPI/blob/afa48a9997abee24064a79d7b7352a8356f9e405/FlaxEngine/Json/JsonCustomSerializers/ExtendedDefaultContractResolver.cs#L39) doesn't return private fields from the base class)

**Steps to reproduce:**

```csharp
[Serializable]
public class BaseClass
{
    [Serialize]
    private string _wellHidden = "you won't find me";
}

[Serializable]
public class DerivedClass : BaseClass
{
    [Serialize]
    private string _derivedHidden = "you might find me, I'm in the derived class";

    public string VeryPublic = "easy to find";

    [NoSerialize]
    public string NotSerialized = "not serialized";
}
```
and
```csharp
Debug.LogError(FlaxEngine.Json.JsonSerializer.Serialize(new BaseClass()));
/* Outputs
{
	"_wellHidden": "you won't find me"
}
*/


Debug.LogError(FlaxEngine.Json.JsonSerializer.Serialize(new DerivedClass()));
/* Outputs, note how _wellHidden does not show up here:
{
	"_derivedHidden": "you might find me, I'm in the derived class",
	"VeryPublic": "easy to find"
}
*/
```

**Minimal reproduction project:**

**Flax version:**

0.4.6181

**Comment by stefnotch** [comment]
Changing the `private` field to `protected` is an acceptable workaround. I'll be going down that route for now.

**Comment by mafiesto4** [comment]
This bug is related to the .Net `Type.GetFields` method itself and we don't want to manually iterate over subtypes to find private fields with those attributes. The best solution is to just use `protected` protection level for child fields that need serialization.
