### ISSUE TITLE
Music Importing into SceneData Folder Crash

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#69]
**Issue description:**

When importing music into a folder and then opening the folder, the FlaxEngine crashes.

**Steps to reproduce:**

1) Find some music, I used a random .mp3 file
2) Open the `Content` folder
3) Drag and drop the music into the `SceneData` sub-folder
![image](https://user-images.githubusercontent.com/10220080/58416102-ce7d5400-8080-11e9-85bc-4e576f170eaf.png)
![image](https://user-images.githubusercontent.com/10220080/58416235-2b790a00-8081-11e9-8708-d10f9aee848e.png)
4) Import it and **wait until it's done**
5) You currently can't see the imported music, because it's in a sub-folder
6) Open the sub-folder. Crash.

Interestingly this doesn't always happen. If it didn't crash, just delete the imported music and try again.

**Minimal reproduction project:**

**Flax version:**

0.4.6181

**Comment by stefnotch** [comment]
Shoutout to [Gnutschi](https://github.com/ivonnegattringer) for finding this buggo.

**Comment by mafiesto4** [comment]
I was unable to reproduce this issue (tried different mp3 files). Maybe it was already fixed for new update. Otherwise, share the audio file that crashes engine.

**Comment by stefnotch** [comment]
Ok, I'll try it out with the next update.

**Comment by stefnotch** [comment]
Seems to be fixed 👍
