### ISSUE TITLE
UI Control selection outline

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#70]
**Issue description:**

It'd be nice if UI controls had a green outline when selecting them. Especially panels, since they are invisible by default.

**Steps to reproduce:**

Add a new panel. You can't see it.

To visualize what it looks like, you have to manually change the background color.

![image](https://user-images.githubusercontent.com/10220080/58728044-4b446100-83e6-11e9-8957-077053793b51.png)

**Minimal reproduction project:**

**Flax version:**

0.4.6181

**Comment by mafiesto4** [comment]
Great idea!
