### ISSUE TITLE
Cannot Open Sln

### ISSUE THREAD

**Issue by mikrokode** [FlaxEngine/FlaxAPI#75]
Friend,

What version of IDE you are using to develop this game?
I using Community version of Visual Studio 2017 and 2015, but cannot open solution with all projects loaded? 

KT Wong

**Comment by mafiesto4** [comment]
You will need to install our extension for Visual Studio that enables working with scripts and adds debugging support. Learn more about here: https://docs.flaxengine.com/manual/scripting/debugging/visual-studio.html

**Comment by mikrokode** [comment]
Friend,

I intend to learn something about game using C#. I hardly to find yours in the internet. I found some resources in C++. Can you share how to build a multiplayer FPS game using C# ? 

KT

**Comment by stefnotch** [comment]
@mikrokode If you're interested in the FlaxEngine or just want to talk a bit about game development, I'd recommend [joining the Discord server](http://discord.flaxengine.com/).

> FPS game 

Check out the FlaxEngine demos, there is a first person shooter demo among them.

> multiplayer 

Flax doesn't natively support multiplayer yet, but you can build it yourself.
