### ISSUE TITLE
Singe.MaxValue in given order crashes engine on Quaternion.Euler

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#8]
Try evaluating
`Actor.Orientation = Quaternion.Euler(Single.MaxValue, -Single.MaxValue, 0);`

Engine crashesh with
![image](https://user-images.githubusercontent.com/5092066/40250399-72a21e48-5ad6-11e8-9fee-f4040ec28e6c.png)

* Windows 10 64x
* Flax 0.1.6154

**Comment by stefnotch** [comment]
Looks like this happens because `Math.Sin(Single.MaxValue * 0.5f)` returns some crazy high value: `1.70141173319264E+38`

(`Math.Sin(Single.MaxValue)` doesn't seem to exhibit this strange behavior.)

**Comment by stefnotch** [comment]
> Acceptable values of a range from approximately -9223372036854775295 **[approximately 9.22337e+18]** to approximately 9223372036854775295. For values outside of this range, the Sin method returns a unchanged rather than throwing an exception.
--[Microsoft Documentation](https://msdn.microsoft.com/en-us/library/system.math.sin.aspx?f=255&MSPPError=-2147217396)

Text in bold are my edits.
