### ISSUE TITLE
Unable to Attach VS 2019 to Flax Editor .6

### ISSUE THREAD

**Issue by devjarmo** [FlaxEngine/FlaxAPI#87]
**Issue description:**
Installed Flax, installed the Flax Editor Extension into VS 2019. When I click "Attach to Flax" the status bar blinks to orange and then back to blue. I receive the following in output window:

![image](https://user-images.githubusercontent.com/35175947/77239481-d292d900-6ba0-11ea-8a1e-92ba4fc71c65.png)

**Steps to reproduce:**
1) Install Flax
2) Install Flax Editor Extension for Visual Studio
3) Create a default project
4) Add a source file to the project.
5) Double click source to open Visual Studio 2019.
6) Click "attach to flax" and observe result.

**Flax version:**
.6

Visual Studio Installed Packages:
[VS2019_Installed_Packages.txt](https://github.com/FlaxEngine/FlaxAPI/files/4364474/VS2019_Installed_Packages.txt)

Log from Flax Editor with -monolog:
[Log_2020_03_21_10_01_40.txt](https://github.com/FlaxEngine/FlaxAPI/files/4364475/Log_2020_03_21_10_01_40.txt)

Log from Visual Studio:
[VisualStudioLog.zip](https://github.com/FlaxEngine/FlaxAPI/files/4364476/VisualStudioLog.zip)

**Comment by devjarmo** [comment]
1) I've tried uninstalling/reinstalling. 
2) I verified bidirectional TCP traffic from the plugin to the editor, they are talking.

**Comment by mafiesto4** [comment]
I just installed fresh VS 2019 Community with individual components:
* C# and Visual Basic Roslyn Compilers
* C# and Visual Basic
* .NET Framework 4.8 targeting pack
* Flax.VS extension
![image](https://user-images.githubusercontent.com/3464853/77248841-f60b6180-6c3c-11ea-92b7-7ab226234fae.png)

Then I opened the project with Flax Editor, added a breakpoint in VS and pressed `Attach To Flax`. Then run the game and see my breakpoint hit in script.
![image](https://user-images.githubusercontent.com/3464853/77248851-08859b00-6c3d-11ea-9934-16cc0e15a453.png)

I just cannot figure out why this problem happens on your PC.

**Comment by devjarmo** [comment]
I uninstalled everything Visual Studio and deleted all folders. I reinstalled only the above components with an additional .NET framework 4.5 (in VS Individual components). I deleted everything Flax and reinstalled.

Took the opportunity to put things all on my SSD too. 

It works now! I am able to use debugger. Something in my previous configuration was preventing this, so I hope this ticket may be of service to others in the future.

Thanks for you assistance mafiesto4. It was nice to jump in and receive help.

**Comment by herocrab** [comment]
Found myself in this scenario again. Flax doesn't like something I have installed... which is annoying because I like to have multiple engines installed.

**Comment by stefnotch** [comment]
Do you happen to have an idea of what it could be that's conflicting with Flax?

**Comment by herocrab** [comment]
I don't, something listed in the installed packages above. I'm re-testing the previous fix now. I primarily use Unity and Stride... but I want to start working more with Flax as it seems like it has all the bases covered and is performant. I'm re-testing the fix action now (uninstall packages and re-install), hopefully that works for the time.

**Comment by herocrab** [comment]
On the re-install I had to install .Net Framework 4.5 to get projects to open correctly. I installed all 4.5 options. It wasn't until after that that projects would open.
