### ISSUE TITLE
Debugger attach issue

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#9]
No reproduction steps as of now, but I have managed to corrupt my project to have 100% reproduction

Attach to Flax returns this error amount of files you have in the project.

![image](https://user-images.githubusercontent.com/5092066/40268095-b04d3fb6-5b67-11e8-9267-642bfb826142.png)

Debugging is imposible for filles (all files?) that has thrown this error. I have only one instance of VS open.

**Comment by mafiesto4** [comment]
Fixed.
