### ISSUE TITLE
Unable to remove keyframes in Animation Player

### ISSUE THREAD

**Issue by devjarmo** [FlaxEngine/FlaxAPI#90]
Searched for an existing issue but did not see one.

**Issue description:**
After spending a couple days animating scenes, it appears that most of the time I cannot delete keyframes. This goes for any keyframe, beginning, middle or end. I've seen it work a few times but in most cases I click "remove keyframe" and nothing happens. This occurs when the game is not running.

**Steps to reproduce:**
1. Create a project.
2. Add animation player and some UI controls to animate.
3. Add several keyframes.
4. Edit keyframes.
5. Attempt to remove keyframes. 

**Minimal reproduction project:**
I'm not on my development workstation, will set a reminder to do this.

**Flax version:**
.6

**Comment by devjarmo** [comment]
As a workaround removing the entire track deletes all keyframes, but this is problematic in large animations.

**Comment by mafiesto4** [comment]
Fixed for the next version (1.0).
