### ISSUE TITLE
Dxgi.dll error when launching editor

### ISSUE THREAD

**Issue by IngmarsLazdinsGit** [FlaxEngine/FlaxAPI#92]
**Issue description:**
When trying to launch FlaxEditor.exe, error pops up: "The procedure entry point CreateDXGIFactory2 could not be located in the dynamic link library dxgi.dll". 

**Environment**
Windows 7  x64, latest available DX/C++ runtimes.

**Flax version:**
0.6 beta (0.5 works fine)

**Comment by mafiesto4** [comment]
Fixed for ver 0.8
