### ISSUE TITLE
Quaternion to Euler documentation

### ISSUE THREAD

**Issue by stefnotch** [FlaxEngine/FlaxAPI#94]
**Issue description:**
The documentation of `Quaternion.EulerAngles` seems to contradict itself
>  z degrees around the z axis, x degrees around the x axis, and y degrees around the y axis (in that order).
> Angles order (xyz)

<https://github.com/FlaxEngine/FlaxAPI/blob/d1389a98deba5eea0765ebf2114f551441fbeab2/FlaxEngine/Math/Quaternion.cs#L216-L219>

**Comment by mafiesto4** [comment]
Thanks for spotting this! Fixed for the next update.
