### ISSUE TITLE
CanvasRootControl Default Size

### ISSUE THREAD

**Issue by jb-perrier** [FlaxEngine/FlaxAPI#95]
The default size of the CanvasRootControl is wrong, for some reason those values are pretty big.
A workaround is to define manually the size ( to the screen size ).

![image](https://user-images.githubusercontent.com/7458848/99185886-f668e780-274c-11eb-9214-7f1126ac72d3.png)
![image](https://user-images.githubusercontent.com/7458848/99185895-02ed4000-274d-11eb-999e-2c9222caa79e.png)

You can easily reproduce it, i'm only using this piece of code in a script.
I've tried with/without children, it doesn't change anything.
I'm running the latest Flax release,

N.B: That's probably why some control like BlurPanel result in a crash related to max texture size.

**Comment by mafiesto4** [comment]
Thanks for report! Fixed for the next update.
