### ISSUE TITLE
Launcher exits without error after giving Admin Privileges

### ISSUE THREAD

**Issue by Muchaszewski** [FlaxEngine/FlaxAPI#97]
**Issue description:**
Launcher exits without error after giving Admin Privileges

**Steps to reproduce:**

1. Open Launcher
2. Add new Version
3. Click Install
4. Config prompt
![image](https://user-images.githubusercontent.com/5092066/99197878-70bd5a00-2795-11eb-8668-6777544e659e.png)
5. Add elevated privileges
6. Crash
(Only happened when tried this first time, so 50% repro)

**Minimal reproduction project:**
None

**Flax version:**
Any

No meaning full debug logs were in the files

**Comment by mafiesto4** [comment]
Is there any `CrashLog.txt` or `Client.log` in `%appdata%/Flax`?

**Comment by Muchaszewski** [comment]
No CrashLog.txt and Client.log was it was overwritten by my trying to see if I can reproduce it.
