### ISSUE TITLE
Crash in Material Graph

### ISSUE THREAD

**Issue by PlasmaDev5** [FlaxEngine/FlaxAPI#99]
**Issue description:**
When adding a normal map parameter to a material the engine crashes. 

**Steps to reproduce:**

1. Open A Project
2. Create a Material
3. Add a Normal Map Param

**Minimal reproduction project:**
From my testing any project is valid

**Flax version:**
0.7 Beta

**Log and Minidump**
[CrashReport.zip](https://github.com/FlaxEngine/FlaxAPI/files/5699447/CrashReport.zip)

**Comment by mafiesto4** [comment]
Fixed.
